Create 20170919_call_notes
ipfs/research-bitswap pull request #4
Opened 2017-09-19 23:53 UTC by miyazono

Add notes from September 19th call

2017-10-20 17:16 UTC, daviddias requested changes
markdown please :)

2017-10-25 05:28 UTC, miyazono commented
better @diasdavid?

2017-10-25 08:13 UTC, daviddias approved these changes

2017-10-25 08:13 UTC, diasdavid commented
thank you :)

2017-10-25 08:13 UTC, merged